### ISSUE TITLE
autofs does not work on Ubuntu 18.10 (Cosmic Cuttlefish)

### ISSUE THREAD

**Issue by hoylen** [qcif/cloud-utils#3]
The autofs package is broken. This is a problem with the distribution/image, and has nothing to do with the _q-storage-setup.sh_ script.

Attempting to install it (with apt-get) produces this error:

```
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
Job for autofs.service failed because the control process exited with error code.
See "systemctl status autofs.service" and "journalctl -xe" for details.
invoke-rc.d: initscript autofs, action "start" failed.
  autofs.service - Automounts filesystems on demand
   Loaded: loaded (/lib/systemd/system/autofs.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2019-01-23 06:46:48 UTC; 18ms ago
  Process: 1945 ExecStart=/usr/sbin/automount $OPTIONS --pid-file /var/run/autofs.pid (code=exited, status=1/FAILURE)

Jan 23 06:46:47 storage-mount-test systemd[1]: Starting Automounts filesystems on demand...
Jan 23 06:46:48 storage-mount-test automount[1945]: /usr/sbin/automount: test mount forbidden or incorrect kernel protocol version, kernel protocol version 5.00 or above required.
Jan 23 06:46:48 storage-mount-test systemd[1]: autofs.service: Control process exited, code=exited status=1
Jan 23 06:46:48 storage-mount-test systemd[1]: autofs.service: Failed with result 'exit-code'.
Jan 23 06:46:48 storage-mount-test systemd[1]: Failed to start Automounts filesystems on demand.
dpkg: error processing package autofs (--configure):
 installed autofs package post-installation script subprocess returned error exit status 1
```

**Work around**

Use Ubuntu 18.04 LTS instead.

Or use ad hoc mounting (with the `--mount` option) and remember to manually re-mount it if the instance is rebooted.

**Comment by th1rtyf0ur** [comment]
Did you install the appropriate linux-modules-extra package? The autofs kernel modules is in there (not the default modules package). Took me ages to figure that one out so posting here in case it helps anyone else w/ the same problem.

`apt -y install linux-modules-extra-$(uname -r)`
should do the trick.

**Comment by hoylen** [comment]
Thank you for that tip.

Unfortunately, I no longer have easy access to a Ubuntu 18.10 environment to properly test this.

FYI, the script does work on the newer Ubuntu 19.10, without needing `linux-modules-extra-5.0.0-13-generic` to be installed (and it wasn't installed by default). Very strange.

_(Leaving this issue open for a few more months/years, in case anyone is still using Ubuntu 18.10.)_
